{% set name = "coolname" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coolname-{{ version }}.tar.gz
  sha256: 8a605be9e48b261ac50e9f258c40adcd4081b9ca0e6f08d39511f77cb2ae55ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - coolname
    - coolname.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alexanderlukanin13/coolname
  summary: Random name and slug generator
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vinisalazar
