{% set name = "coolname" %}
{% set version = "5.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coolname-{{ version }}.tar.gz
  sha256: 594bc6c98ebc75ddd51c0ce10efbb5d2556c14eac60b5b36900dfdd5db20eecf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - coolname
    - coolname.data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alexanderlukanin13/coolname
  summary: Random name and slug generator
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vinisalazar
